name: Archive links

on:
  schedule:
    - cron: "0 0 15 * *" # Runs at midnight on the 15th of every month
  push:
    branches:
      - main
    paths:
      - "manifest.txt"

jobs:
  archive-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: make install

      - name: Archive links in manifest
        run: cat manifest.txt | grep -vE '^\s*(#|$)' | sort -u | shuf | xargs -n 4 -P 4 rxv

      - name: Upload log
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: "*.log"
